imageType:
  Original: {}
  LoG:
    sigma: [1.0, 2.0, 3.0]
  Wavelet: {}
  Gradient: {}
  Square: {}
  SquareRoot: {}
  Exponential: {}
  Logarithm: {}

featureClass:
  shape:  
  firstorder:  
  glcm:  
    - 'Autocorrelation'
    - 'JointAverage'
    - 'ClusterProminence'
    - 'ClusterShade'
    - 'ClusterTendency'
    - 'Contrast'
    - 'Correlation'
    - 'DifferenceAverage'
    - 'DifferenceEntropy'
    - 'DifferenceVariance'
    - 'JointEnergy'
    - 'JointEntropy'
    - 'Imc1'
    - 'Imc2'
    - 'Idm'
    - 'Idmn'
    - 'Id'
    - 'Idn'
    - 'InverseVariance'
    - 'MaximumProbability'
    - 'SumEntropy'
    - 'SumSquares'
  glrlm:  
  glszm:  
  gldm: 
  ngtdm:  

setting:
  interpolator: 'sitkBSpline'
  resampledPixelSpacing: [2, 2, 2]
  padDistance: 10  
  binWidth: 25
  voxelArrayShift: 1000  
  label: 1